✨ feat(Pointer Schema): Better validation errors for pointer schema.
ethdebug/format pull request #88
Opened 2024-04-20 03:20 UTC by raxhvl

Closes #87.

2024-04-20 18:38 UTC, gnidan requested changes
Fix needed to get the build to pass. Thanks for investigating this!

2024-04-20 18:38 UTC, gnidan commented on schemas/pointer.schema.yaml
> +    location: {}
This is probably failing because here's the right way to do this:

```suggestion
    required: [location]
```

This is a bit non-intuitive, but think of `if` as a stand-alone schema. A schema that just defines `location` as an optional property matches every object, whether or not it has `location`. We want to check only for schemas that definitely have `location`, so our `if` schema must check specifically for it being required.

Let me know if this doesn't make sense and I can try explaining it a different way.

2024-04-21 06:02 UTC, raxhvl commented
@gnidan my bad I thought `yarn start` runs tests too. I'll be sure to run `yarn test` when pushing changes.  Your suggestions fixes the test; your explanation was intuitive too. Thanks!

2024-04-21 14:06 UTC, gnidan commented
Awesome! Weird about `yarn start` - are you running it from the repo root?

2024-04-21 14:06 UTC, gnidan approved these changes

2024-04-21 14:07 UTC, merged

2024-04-22 06:46 UTC, raxhvl commented
> Awesome! Weird about `yarn start` - are you running it from the repo root?

Yep.